In [ ]:
#importing all the libraries
import pandas as pd
import numpy as np
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [435]:
df = pd.read_csv("/Users/gauravbohra/Documents/practice/Project/DA/dff4d804-5031-443a-8409-8344efd0e5c8.csv")

In [436]:
#Reading first few rows to understand the data
df.head()

,_id,case_enquiry_id,open_dt,sla_target_dt,closed_dt,on_time,case_status,closure_reason,case_title,subject,reason,type,queue,department,submitted_photo,closed_photo,location,fire_district,pwd_district,city_council_district,police_district,neighborhood,neighborhood_services_district,ward,precinct,location_street_name,location_zipcode,latitude,longitude,geom_4326,source
0,1,101005463183,2024-05-14 13:33:28,2024-05-17 04:30:00,2024-05-15 02:58:54,ONTIME,Closed,Case Closed. Closed date : Wed May 15 06:58:54...,Improper Storage of Trash (Barrels),Public Works Department,Code Enforcement,Improper Storage of Trash (Barrels),PWDx_Code Enforcement,PWDx,NaN,https://spot-boston-res.cloudinary.com/image/u...,160-162 Liverpool St East Boston MA 02128,1,09,1,A7,East Boston,1,Ward 1,0104,160-162 Liverpool St,2128.0,42.373879,-71.039800,0101000020E610000067D9DA168CC251C0813C8648DB2F...,Citizens Connect App
1,2,101005463184,2024-05-14 13:33:53,2024-07-22 04:30:00,2024-05-24 12:34:37,ONTIME,Closed,Case Closed. Closed date : Fri May 24 16:34:37...,Graffiti Removal,Property Management,Graffiti,Graffiti Removal,PROP_GRAF_GraffitiRemoval,PROP,NaN,https://spot-boston-res.cloudinary.com/image/u...,1660 Dorchester Ave Dorchester MA 02122,7,07,3,C11,Dorchester,7,Ward 16,1604,1660 Dorchester Ave,2122.0,42.293929,-71.061822,0101000020E610000042C2E1E2F4C351C06A7817749F25...,Citizens Connect App
2,3,101005837387,2024-12-31 02:11:57,2025-01-01 03:30:00,NaN,OVERDUE,Open,,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,Parking Enforcement,BTDT_Parking Enforcement,BTDT,NaN,NaN,416 Belgrade Ave West Roxbury MA 02132,12,06,6,E5,West Roxbury,12,Ward 20,2011,416 Belgrade Ave,2132.0,42.285790,-71.149281,0101000020E6100000A24B1DD18DC951C0FDE05CC19424...,Citizens Connect App
3,4,101005287893,2024-02-07 04:01:41,2024-02-09 04:01:43,2024-02-07 05:48:33,ONTIME,Closed,Case Closed. Closed date : Wed Feb 07 10:48:33...,Improper Storage of Trash (Barrels),Public Works Department,Code Enforcement,Improper Storage of Trash (Barrels),PWDx_Code Enforcement,PWDx,NaN,https://spot-boston-res.cloudinary.com/image/u...,3 Saint Charles St Boston MA 02116,4,1C,2,D4,South End,6,Ward 5,0501,3 Saint Charles St,2116.0,42.347130,-71.071811,0101000020E61000007395138B98C451C03EAD9FBD6E2C...,Citizens Connect App
4,5,101005331785,2024-02-28 08:06:00,2024-02-29 08:06:25,2024-03-04 09:07:57,OVERDUE,Closed,Case Closed. Closed date : 2024-03-04 14:07:57...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,Parking Enforcement,BTDT_Parking Enforcement,BTDT,NaN,NaN,47 Torrey St Dorchester MA 02124,8,07,4,B3,Dorchester,9,Ward 17,1708,47 Torrey St,2124.0,42.287380,-71.073564,0101000020E6100000AE634444B5C451C03EDE5DDAC824...,Constituent Call

In [438]:
#Noting down all the columns
df.columns.values

array(['_id', 'case_enquiry_id', 'open_dt', 'sla_target_dt', 'closed_dt',
       'on_time', 'case_status', 'closure_reason', 'case_title',
       'subject', 'reason', 'type', 'queue', 'department',
       'submitted_photo', 'closed_photo', 'location', 'fire_district',
       'pwd_district', 'city_council_district', 'police_district',
       'neighborhood', 'neighborhood_services_district', 'ward',
       'precinct', 'location_street_name', 'location_zipcode', 'latitude',
       'longitude', 'geom_4326', 'source'], dtype=object)

# EDA

In [439]:
# Dropping geom_4326 column becuase according to the business requirement it is not needed
df = df.drop("geom_4326",axis=1)

In [440]:
# Checking the dataset after dropping the column
df.head(2)

,_id,case_enquiry_id,open_dt,sla_target_dt,closed_dt,on_time,case_status,closure_reason,case_title,subject,reason,type,queue,department,submitted_photo,closed_photo,location,fire_district,pwd_district,city_council_district,police_district,neighborhood,neighborhood_services_district,ward,precinct,location_street_name,location_zipcode,latitude,longitude,source
0,1,101005463183,2024-05-14 13:33:28,2024-05-17 04:30:00,2024-05-15 02:58:54,ONTIME,Closed,Case Closed. Closed date : Wed May 15 06:58:54...,Improper Storage of Trash (Barrels),Public Works Department,Code Enforcement,Improper Storage of Trash (Barrels),PWDx_Code Enforcement,PWDx,NaN,https://spot-boston-res.cloudinary.com/image/u...,160-162 Liverpool St East Boston MA 02128,1,09,1,A7,East Boston,1,Ward 1,0104,160-162 Liverpool St,2128.0,42.373879,-71.039800,Citizens Connect App
1,2,101005463184,2024-05-14 13:33:53,2024-07-22 04:30:00,2024-05-24 12:34:37,ONTIME,Closed,Case Closed. Closed date : Fri May 24 16:34:37...,Graffiti Removal,Property Management,Graffiti,Graffiti Removal,PROP_GRAF_GraffitiRemoval,PROP,NaN,https://spot-boston-res.cloudinary.com/image/u...,1660 Dorchester Ave Dorchester MA 02122,7,07,3,C11,Dorchester,7,Ward 16,1604,1660 Dorchester Ave,2122.0,42.293929,-71.061822,Citizens Connect App

In [441]:
filter = df["sla_target_dt"].isnull()
select_col = df[["open_dt", "sla_target_dt", "closed_dt", "on_time", "case_status"]]
output = select_col[filter]
print(output)

# EDA Note: SLA Target and On-Time Flag Behavior

# During exploratory data analysis of the Boston 311 dataset, I observed a consistent relationship between the sla_target_dt and on_time fields. 
# For records where sla_target_dt is NULL, the on_time flag is always set to TRUE, regardless of whether the case is currently OPEN or CLOSED. 
# This indicates that for these cases, no SLA target was defined by the source system, and therefore SLA compliance is not applicable.

# Additionally, case status is determined independently of SLA logic: cases with a populated closed_dt are marked as CLOSED, while cases with 
# a NULL closed_dt are marked as OPEN. The on_time flag in SLA-null cases should not be interpreted as successful SLA compliance, but rather 
# as a default or non-applicable state.

# Implication for analysis:
# SLA compliance metrics should be calculated only for cases where sla_target_dt is not NULL. Including SLA-null cases would artificially 
# inflate on-time performance and misrepresent operational effectiveness. For accurate reporting, SLA adherence should be derived by comparing 
# closed_dt (or current date for open cases) against sla_target_dt, and SLA-null cases should be excluded from compliance calculations.

                    open_dt sla_target_dt            closed_dt on_time  \
16      2024-04-08 11:58:00           NaN  2024-04-08 13:01:48  ONTIME
43      2024-04-08 11:09:17           NaN  2024-04-08 13:30:46  ONTIME
44      2024-04-08 11:10:05           NaN  2024-04-08 11:38:16  ONTIME
46      2024-05-06 10:39:36           NaN  2024-05-07 10:59:38  ONTIME
62      2024-05-14 13:39:00           NaN  2024-05-15 13:05:59  ONTIME
82      2024-03-19 06:57:55           NaN  2024-03-19 07:10:23  ONTIME
95      2024-05-14 16:02:00           NaN  2024-05-15 13:07:20  ONTIME
100     2024-07-22 13:33:00           NaN  2024-07-23 03:24:26  ONTIME
106     2024-03-19 05:40:10           NaN  2024-03-19 05:49:12  ONTIME
112     2024-03-19 08:03:00           NaN  2024-05-02 00:52:55  ONTIME
133     2024-07-22 14:07:00           NaN  2024-08-09 00:24:28  ONTIME
134     2024-07-22 14:11:00           NaN  2024-07-22 14:37:14  ONTIME
143     2024-04-17 13:55:00           NaN  2024-12-24 02:10:43  ONTIME
151     2024-05-06 11:15:00           NaN  2024-05-06 13:13:09  ONTIME
157     2024-05-23 04:00:04           NaN  2024-05-23 05:00:16  ONTIME
167     2024-04-17 13:12:00           NaN  2024-04-18 08:01:23  ONTIME
169     2024-04-17 13:26:58           NaN  2024-04-17 15:12:38  ONTIME
180     2024-03-19 12:03:44           NaN  2024-03-19 13:16:03  ONTIME
194     2024-09-27 11:11:00           NaN  2024-09-27 11:41:57  ONTIME
202     2024-04-18 03:43:00           NaN                  NaN  ONTIME
217     2024-04-17 12:01:00           NaN  2024-04-18 08:02:26  ONTIME
225     2024-03-19 09:57:00           NaN  2024-03-19 10:26:42  ONTIME
232     2024-05-23 04:21:33           NaN  2024-05-23 04:41:40  ONTIME
236     2024-03-19 11:50:45           NaN  2024-03-19 13:16:27  ONTIME
252     2024-03-19 11:14:48           NaN  2024-03-19 14:37:28  ONTIME
261     2024-09-19 03:15:07           NaN  2024-09-19 05:27:54  ONTIME
278     2024-08-14 12:56:00           NaN                  NaN  ONTIME
281     2024-01-26 04:37:00           NaN                  NaN  ONTIME
287     2024-03-19 10:29:45           NaN  2024-03-19 10:42:18  ONTIME
290     2024-03-19 09:39:00           NaN  2024-03-19 10:07:17  ONTIME
293     2024-05-23 04:35:00           NaN                  NaN  ONTIME
300     2024-10-06 07:29:23           NaN  2024-10-06 08:18:03  ONTIME
304     2024-01-26 06:34:57           NaN  2024-01-26 07:47:16  ONTIME
336     2024-01-06 05:10:36           NaN  2024-01-06 05:51:00  ONTIME
341     2024-01-26 05:10:00           NaN                  NaN  ONTIME
342     2024-10-06 07:32:00           NaN  2024-10-07 08:10:10  ONTIME
366     2024-08-14 15:20:16           NaN  2024-08-14 16:47:38  ONTIME
367     2024-12-09 04:39:00           NaN  2024-12-11 07:36:08  ONTIME
422     2024-09-19 04:00:32           NaN  2024-09-19 05:53:23  ONTIME
433     2024-01-27 02:36:35           NaN  2024-01-30 09:38:02  ONTIME
435     2024-01-27 03:19:49           NaN  2024-01-27 03:35:05  ONTIME
441     2024-01-26 12:09:06           NaN  2024-01-26 14:17:32  ONTIME
446     2024-01-26 16:31:03           NaN  2024-01-27 02:23:04  ONTIME
447     2024-01-26 19:13:00           NaN                  NaN  ONTIME
450     2024-12-09 09:46:02           NaN  2024-12-09 09:57:47  ONTIME
452     2024-12-09 10:18:12           NaN  2024-12-09 10:40:53  ONTIME
468     2024-11-14 10:33:27           NaN  2024-11-14 10:35:14  ONTIME
469     2024-12-09 11:06:30           NaN  2024-12-09 11:46:40  ONTIME
470     2024-12-09 11:08:00           NaN  2024-12-09 11:52:52  ONTIME
484     2024-12-09 08:36:00           NaN  2024-12-09 08:51:03  ONTIME
497     2024-02-28 14:20:00           NaN                  NaN  ONTIME
518     2024-01-09 02:08:00           NaN                  NaN  ONTIME
528     2024-02-29 02:45:00           NaN  2024-02-29 03:17:01  ONTIME
532     2024-02-29 03:53:57           NaN  2024-02-29 03:54:08  ONTIME
550     2024-01-27 07:04:23           NaN  2024-01-27 07:49:25  ONTIME
556     2024-12-31 05:17:18           NaN  2024-12-31 05:54:51  ONTIME
560     2024-12-31 05:24:28           NaN  2024-12-31 05:54:46  ONTIME
570     2024-02-29 03:47:20           NaN  2024-02-29 05:16:14  ONTIME
575     2024-02-29 04:56:00           NaN  2024-03-04 06:24:53  ONTIME
584     2024-02-29 06:07:00           NaN  2024-02-29 06:25:59  ONTIME
585     2024-02-29 06:12:10           NaN  2024-02-29 06:46:09  ONTIME
597     2024-02-29 07:10:00           NaN  2024-03-04 06:12:06  ONTIME
617     2024-02-28 12:13:46           NaN  2024-02-28 12:21:17  ONTIME
628     2024-02-28 11:32:36           NaN  2024-02-28 12:17:03  ONTIME
648     2024-02-29 10:37:00           NaN  2024-03-12 07:03:29  ONTIME
664     2024-01-27 05:56:00           NaN  2024-01-27 06:22:29  ONTIME
669     2024-01-27 06:32:17           NaN  2024-01-30 10:55:15  ONTIME
676     2024-01-27 07:50:00           NaN  2024-01-31 06:30:51  ONTIME
684     2024-01-27 08:37:00           NaN  2024-01-29 04:02:09  ONTIME
688     2024-01-27 09:18:00           NaN                  NaN  ONTIME
689     2024-01-27 09:24:00           NaN  2024-01-31 06:30:51  ONTIME
690     2024-01-27 09:42:42           NaN  2024-01-27 10:09:05  ONTIME
697     2024-02-07 03:05:00           NaN  2024-02-07 03:36:29  ONTIME
705     2024-11-14 12:39:16           NaN  2024-11-14 14:26:13  ONTIME
720     2024-01-01 02:54:55           NaN  2024-01-01 04:43:59  ONTIME
722     2024-01-01 03:39:00           NaN  2024-01-03 11:23:31  ONTIME
723     2024-01-01 03:46:02           NaN  2024-01-01 03:47:32  ONTIME
724     2024-01-01 04:07:00           NaN  2024-01-17 02:51:46  ONTIME
727     2024-01-01 05:07:53           NaN  2024-01-01 07:17:15  ONTIME
738     2024-01-01 07:22:44           NaN  2024-01-03 05:50:21  ONTIME
748     2024-01-01 09:25:00           NaN  2024-01-01 10:30:04  ONTIME
764     2024-01-01 16:45:51           NaN  2024-01-02 05:27:37  ONTIME
769     2024-01-03 03:40:55           NaN  2024-01-03 04:04:41  ONTIME
807     2024-01-02 00:15:00           NaN  2024-01-02 02:46:29  ONTIME
828     2024-01-02 05:34:00           NaN                  NaN  ONTIME
833     2024-01-04 07:59:35           NaN  2024-01-04 08:20:00  ONTIME
844     2024-01-04 09:07:05           NaN  2024-01-05 02:19:32  ONTIME
865     2024-01-04 12:35:30           NaN  2024-01-04 12:54:23  ONTIME
867     2024-01-04 12:47:00           NaN  2024-01-05 04:18:31  ONTIME
870     2024-01-05 07:56:00           NaN                  NaN  ONTIME
876     2024-01-05 08:41:00           NaN  2024-01-06 07:30:24  ONTIME
903     2024-01-02 07:15:21           NaN  2024-01-02 07:43:52  ONTIME
904     2024-01-02 07:15:50           NaN  2024-01-02 07:42:57  ONTIME
1006    2024-01-05 11:59:40           NaN  2024-01-08 03:35:19  ONTIME
1040    2024-01-06 04:27:00           NaN  2024-01-06 05:16:55  ONTIME
1053    2024-01-06 06:20:03           NaN  2024-01-06 09:56:15  ONTIME
1062    2024-01-06 07:18:56           NaN  2024-01-06 08:51:20  ONTIME
1082    2024-01-08 09:19:00           NaN  2024-01-09 02:22:35  ONTIME
1121    2024-01-18 03:50:00           NaN  2024-01-18 11:01:58  ONTIME
1132    2024-01-13 02:55:00           NaN                  NaN  ONTIME
1134    2024-01-13 03:47:00           NaN                  NaN  ONTIME
1138    2024-01-13 04:19:00           NaN  2024-02-06 06:12:03  ONTIME
1142    2024-01-08 11:04:00           NaN                  NaN  ONTIME
1156    2024-01-18 05:06:00           NaN                  NaN  ONTIME
1191    2024-01-09 02:09:00           NaN                  NaN  ONTIME
1199    2024-01-18 05:43:41           NaN                  NaN  ONTIME
1240    2024-01-13 04:45:52           NaN  2024-01-13 06:19:07  ONTIME
1253    2024-01-18 09:17:55           NaN  2024-01-18 09:39:08  ONTIME
1267    2024-01-05 03:29:00           NaN  2024-01-05 03:48:41  ONTIME
1311    2024-01-06 13:33:13           NaN  2024-01-07 02:44:32  ONTIME
1325    2024-01-05 07:05:00           NaN  2024-01-06 16:34:35  ONTIME
1345    2024-01-12 06:12:23           NaN  2024-01-16 10:02:19  ONTIME
1350    2024-01-12 06:48:45           NaN  2024-01-16 10:10:50  ONTIME
1359    2024-01-07 06:57:04           NaN  2024-01-07 09:01:22  ONTIME
1362    2024-01-07 08:00:07           NaN  2024-01-07 11:42:57  ONTIME
1367    2024-01-07 11:09:28           NaN  2024-01-08 01:21:29  ONTIME
1372    2024-01-07 11:22:00           NaN  2024-01-07 13:33:33  ONTIME
1379    2024-01-07 15:37:15           NaN  2024-01-07 15:42:11  ONTIME
1381    2024-01-07 22:45:00           NaN  2024-01-17 02:51:46  ONTIME
1389    2024-01-08 03:15:00           NaN                  NaN  ONTIME
1402    2024-01-17 14:55:29           NaN                  NaN  ONTIME
1414    2024-01-08 04:45:00           NaN  2024-01-08 07:48:06  ONTIME
1429    2024-01-12 08:05:00           NaN  2024-01-12 09:14:08  ONTIME
1435    2024-01-12 08:38:00           NaN  2024-01-13 05:52:49  ONTIME
1460    2024-01-12 10:24:00           NaN                  NaN  ONTIME
1491    2024-01-18 01:54:00           NaN                  NaN  ONTIME
1510    2024-01-10 12:39:00           NaN  2024-01-11 08:00:55  ONTIME
1545    2024-01-15 04:54:42           NaN  2024-01-15 07:08:51  ONTIME
1546    2024-01-15 05:19:00           NaN                  NaN  ONTIME
1560    2024-01-19 11:44:08           NaN                  NaN  ONTIME
1563    2024-01-19 12:25:00           NaN  2024-01-22 04:23:59  ONTIME
1568    2024-01-15 07:29:00           NaN  2024-01-17 08:54:14  ONTIME
1611    2024-01-11 05:03:00           NaN  2024-01-11 05:36:57  ONTIME
1706    2024-01-16 06:04:00           NaN  2024-01-16 09:40:04  ONTIME
1717    2024-01-11 10:00:33           NaN  2024-01-11 10:49:20  ONTIME
1718    2024-01-11 10:12:43           NaN  2024-01-11 11:13:00  ONTIME
1723    2024-01-11 10:20:40           NaN  2024-01-16 10:10:10  ONTIME
1740    2024-01-20 04:58:22           NaN                  NaN  ONTIME
1754    2024-01-20 08:59:00           NaN                  NaN  ONTIME
1765    2024-01-16 10:09:00           NaN                  NaN  ONTIME
1766    2024-01-16 10:14:00           NaN                  NaN  ONTIME
1770    2024-01-16 11:12:00           NaN                  NaN  ONTIME
1790    2024-01-16 12:44:03           NaN  2024-01-17 06:43:00  ONTIME
1805    2024-01-20 18:58:21           NaN                  NaN  ONTIME
1809    2024-01-21 04:22:56           NaN  2024-01-21 04:33:24  ONTIME
1853    2024-01-12 02:57:26           NaN  2024-01-12 04:08:12  ONTIME
1856    2024-01-12 03:27:00           NaN                  NaN  ONTIME
1860    2024-01-16 18:05:00           NaN  2024-01-16 18:23:25  ONTIME
1862    2024-01-16 19:17:00           NaN                  NaN  ONTIME
1879    2024-01-12 04:29:00           NaN                  NaN  ONTIME
1884    2024-01-12 04:57:00           NaN                  NaN  ONTIME
1890    2024-01-02 09:42:00           NaN                  NaN  ONTIME
1906    2024-01-02 10:26:00           NaN  2024-01-03 06:15:21  ONTIME
1940    2024-01-17 03:45:00           NaN                  NaN  ONTIME
1971    2024-01-02 11:08:00           NaN  2024-01-02 11:46:09  ONTIME
1978    2024-01-02 12:25:00           NaN  2024-01-03 03:23:07  ONTIME
2020    2024-01-25 02:00:00           NaN  2024-01-25 02:06:36  ONTIME
2069    2024-01-17 09:15:00           NaN  2024-01-17 09:51:07  ONTIME
2071    2024-01-17 10:05:00           NaN  2024-01-17 11:20:06  ONTIME
2097    2024-01-25 08:58:00           NaN                  NaN  ONTIME
2115    2024-01-17 12:09:32           NaN                  NaN  ONTIME
2123    2024-01-17 12:48:58           NaN  2024-01-17 12:49:49  ONTIME
2134    2024-01-22 04:05:28           NaN  2024-01-22 04:26:27  ONTIME
2154    2024-01-25 09:21:57           NaN                  NaN  ONTIME
2168    2024-02-07 03:20:28           NaN  2024-02-07 03:47:30  ONTIME
2243    2024-02-01 02:42:25           NaN  2024-02-01 04:06:02  ONTIME
2266    2024-02-01 03:20:17           NaN  2024-02-01 03:32:54  ONTIME
2273    2024-01-22 09:19:20           NaN  2024-01-22 09:59:18  ONTIME
2329    2024-02-01 04:20:47           NaN  2024-02-01 04:37:51  ONTIME
2330    2024-02-07 04:59:28           NaN  2024-02-07 06:07:40  ONTIME
2362    2024-01-03 03:35:00           NaN  2024-01-03 09:12:35  ONTIME
2370    2024-02-07 05:23:20           NaN  2024-02-07 05:52:25  ONTIME
2377    2024-01-03 04:06:42           NaN  2024-01-03 04:33:28  ONTIME
2382    2024-01-03 04:20:00           NaN                  NaN  ONTIME
2420    2024-01-22 18:36:30           NaN  2024-01-22 18:36:36  ONTIME
2421    2024-01-22 19:01:00           NaN  2024-01-31 06:30:51  ONTIME
2422    2024-01-03 04:39:00           NaN  2024-01-03 05:24:22  ONTIME
2423    2024-01-03 04:58:00           NaN  2024-01-03 10:51:40  ONTIME
2424    2024-01-03 05:05:00           NaN                  NaN  ONTIME
2443    2024-01-26 08:04:00           NaN  2024-02-09 09:03:16  ONTIME
2456    2024-02-01 04:52:59           NaN  2024-02-01 04:53:35  ONTIME
2464    2024-02-01 06:06:00           NaN  2024-02-01 07:03:26  ONTIME
2470    2024-01-26 09:41:00           NaN  2024-01-29 04:24:17  ONTIME
2472    2024-01-26 10:07:00           NaN                  NaN  ONTIME
2490    2024-01-26 13:26:00           NaN                  NaN  ONTIME
2526    2024-01-23 00:28:00           NaN  2024-01-31 06:30:51  ONTIME
2544    2024-01-09 03:23:57           NaN  2024-01-09 04:56:37  ONTIME
2565    2024-01-09 06:25:00           NaN                  NaN  ONTIME
2611    2024-01-03 11:27:00           NaN  2024-01-04 03:44:07  ONTIME
2654    2024-01-23 04:03:00           NaN  2024-02-01 09:20:40  ONTIME
2667    2024-01-23 05:46:39           NaN  2024-01-23 06:26:07  ONTIME
2673    2024-01-27 03:18:07           NaN  2024-01-27 03:26:29  ONTIME
2674    2024-01-27 03:20:00           NaN  2024-01-31 06:30:51  ONTIME
2680    2024-01-27 04:26:00           NaN  2024-01-29 09:15:47  ONTIME
2712    2024-01-27 05:57:00           NaN  2024-01-29 05:06:01  ONTIME
2735    2024-01-23 08:57:15           NaN  2024-01-23 09:23:52  ONTIME
2774    2024-01-27 10:39:00           NaN  2024-01-31 00:41:04  ONTIME
2786    2024-01-01 04:44:10           NaN  2024-01-01 12:53:34  ONTIME
2788    2024-01-01 04:49:22           NaN  2024-01-01 06:28:49  ONTIME
2801    2024-01-04 03:24:21           NaN  2024-01-04 03:44:33  ONTIME
2820    2024-02-01 08:38:00           NaN  2024-02-01 09:31:06  ONTIME
2829    2024-02-01 09:51:47           NaN  2024-02-01 10:07:11  ONTIME
2842    2024-02-01 11:41:00           NaN  2024-02-02 11:04:57  ONTIME
2864    2024-01-23 11:06:00           NaN                  NaN  ONTIME
2866    2024-01-23 11:40:00           NaN  2024-01-26 09:16:21  ONTIME
2882    2024-01-04 03:42:52           NaN  2024-01-05 06:09:07  ONTIME
2906    2024-01-28 01:14:00           NaN  2024-01-29 04:36:28  ONTIME
2909    2024-01-28 02:46:12           NaN  2024-01-28 05:28:04  ONTIME
2912    2024-01-28 03:27:00           NaN  2024-01-29 04:28:46  ONTIME
2935    2024-01-04 04:30:00           NaN                  NaN  ONTIME
2942    2024-01-04 05:01:00           NaN  2024-02-23 12:31:44  ONTIME
2974    2024-01-24 04:35:31           NaN  2024-01-24 04:56:11  ONTIME
3000    2024-01-09 12:21:00           NaN  2024-01-09 14:25:36  ONTIME
3002    2024-01-09 12:59:00           NaN  2024-01-09 13:47:27  ONTIME
3012    2024-01-09 23:10:00           NaN  2024-01-17 07:45:04  ONTIME
3027    2024-02-02 01:49:00           NaN  2024-02-05 07:18:44  ONTIME
3051    2024-01-04 08:12:00           NaN  2024-01-04 09:02:57  ONTIME
3061    2024-02-02 02:29:00           NaN  2024-02-02 03:24:20  ONTIME
3072    2024-02-02 04:01:45           NaN  2024-02-02 04:15:43  ONTIME
3089    2024-01-28 08:23:02           NaN  2024-02-02 10:04:13  ONTIME
3101    2024-01-01 11:31:00           NaN                  NaN  ONTIME
3124    2024-01-24 09:51:00           NaN                  NaN  ONTIME
3128    2024-01-24 10:06:00           NaN                  NaN  ONTIME
3146    2024-01-04 10:39:05           NaN  2024-01-04 11:56:14  ONTIME
3161    2024-01-28 13:47:24           NaN  2024-01-29 01:29:39  ONTIME
3178    2024-01-10 03:17:00           NaN  2024-01-11 07:43:31  ONTIME
3204    2024-01-10 03:41:00           NaN  2024-01-11 09:24:13  ONTIME
3217    2024-01-04 14:24:27           NaN  2024-01-05 01:46:45  ONTIME
3248    2024-02-02 07:02:00           NaN  2024-02-02 07:17:34  ONTIME
3284    2024-01-29 03:22:27           NaN  2024-01-29 03:53:04  ONTIME
3294    2024-01-29 04:08:00           NaN                  NaN  ONTIME
3305    2024-01-24 14:35:38           NaN  2024-01-25 09:37:07  ONTIME
3334    2024-01-02 08:37:00           NaN                  NaN  ONTIME
3336    2024-01-02 08:58:24           NaN  2024-01-02 09:16:39  ONTIME
3337    2024-01-02 09:02:00           NaN  2024-01-08 05:55:25  ONTIME
3344    2024-01-10 05:12:50           NaN  2024-01-10 05:13:52  ONTIME
3349    2024-01-10 05:48:00           NaN  2024-01-17 01:47:09  ONTIME
3363    2024-01-05 03:58:47           NaN  2024-01-05 04:19:56  ONTIME
3365    2024-01-05 04:02:00           NaN  2024-01-05 05:14:42  ONTIME
3366    2024-01-05 04:04:00           NaN  2024-01-08 08:30:09  ONTIME
3394    2024-01-10 07:16:00           NaN  2024-01-12 07:08:57  ONTIME
3398    2024-01-10 07:42:00           NaN  2024-01-10 09:37:48  ONTIME
3416    2024-02-02 09:13:00           NaN                  NaN  ONTIME
3417    2024-02-02 09:28:00           NaN                  NaN  ONTIME
3423    2024-02-02 09:52:45           NaN  2024-02-02 11:31:48  ONTIME
3424    2024-02-02 09:57:04           NaN  2024-02-02 11:31:01  ONTIME
3433    2024-01-29 04:17:00           NaN  2024-02-14 09:57:57  ONTIME
3434    2024-01-29 04:20:00           NaN                  NaN  ONTIME
3437    2024-01-29 04:58:00           NaN                  NaN  ONTIME
3445    2024-01-29 05:34:27           NaN  2024-01-29 06:37:29  ONTIME
3446    2024-01-29 05:41:14           NaN  2024-01-29 06:43:00  ONTIME
3453    2024-01-29 07:28:37           NaN  2024-01-30 09:46:19  ONTIME
3465    2024-02-02 11:04:09           NaN  2024-02-02 11:47:07  ONTIME
3470    2024-02-02 11:27:00           NaN  2024-02-02 13:38:15  ONTIME
3479    2024-02-06 11:05:00           NaN                  NaN  ONTIME
3486    2024-01-13 11:37:00           NaN                  NaN  ONTIME
3503    2024-01-05 04:41:00           NaN  2024-01-06 16:17:44  ONTIME
3526    2024-02-02 11:57:00           NaN                  NaN  ONTIME
3533    2024-02-02 15:42:00           NaN  2024-02-05 07:28:23  ONTIME
3561    2024-01-05 07:31:00           NaN  2024-01-10 07:06:51  ONTIME
3569    2024-01-05 09:28:47           NaN  2024-01-09 06:38:36  ONTIME
3605    2024-02-06 12:23:00           NaN  2024-02-06 13:08:28  ONTIME
3629    2024-01-14 04:14:00           NaN  2024-01-14 04:35:36  ONTIME
3682    2024-01-14 07:41:00           NaN                  NaN  ONTIME
3735    2024-01-30 01:17:54           NaN  2024-01-30 01:44:50  ONTIME
3755    2024-02-07 04:31:06           NaN  2024-02-07 06:10:20  ONTIME
3758    2024-01-14 12:07:00           NaN  2024-01-17 02:51:46  ONTIME
3770    2024-01-14 14:59:00           NaN                  NaN  ONTIME
3775    2024-01-05 10:52:00           NaN                  NaN  ONTIME
3781    2024-01-05 12:18:00           NaN  2024-01-08 07:46:43  ONTIME
3815    2024-01-11 02:16:00           NaN  2024-01-11 04:15:40  ONTIME
3854    2024-01-15 03:06:00           NaN  2024-01-19 09:56:57  ONTIME
3860    2024-01-15 04:14:27           NaN  2024-01-15 04:17:51  ONTIME
3869    2024-01-30 07:27:00           NaN                  NaN  ONTIME
3872    2024-01-30 07:50:00           NaN                  NaN  ONTIME
3873    2024-01-30 07:57:00           NaN  2024-02-09 09:32:27  ONTIME
3876    2024-01-30 08:30:00           NaN  2024-01-31 06:50:15  ONTIME
3877    2024-01-30 08:34:52           NaN  2024-01-30 09:05:43  ONTIME
3921    2024-02-07 08:27:00           NaN  2024-03-12 07:03:28  ONTIME
3940    2024-02-03 10:32:10           NaN  2024-02-03 11:27:17  ONTIME

In [442]:
# Checking columns name and changing them based on data dictionary 
df.head(5)
df.rename(columns={"_id":"system_generated_id", "case_enquiry_id":"case_id", "open_dt":"open_date",
                   "sla_target_dt":"sla_target_date", "closed_dt":"closed_date",
                   "case_title":"case_topic", "pwd_district":"public_works_district",
                   "department":"assignment_department", "subject":"assigned_department",
                   "reason":"assigned_team", "type":"service_name",
                   "assignment_department":"assigned_department_code"},inplace=True)

In [443]:
df.head()

,system_generated_id,case_id,open_date,sla_target_date,closed_date,on_time,case_status,closure_reason,case_topic,assigned_department,assigned_team,service_name,queue,assignment_department,submitted_photo,closed_photo,location,fire_district,public_works_district,city_council_district,police_district,neighborhood,neighborhood_services_district,ward,precinct,location_street_name,location_zipcode,latitude,longitude,source
0,1,101005463183,2024-05-14 13:33:28,2024-05-17 04:30:00,2024-05-15 02:58:54,ONTIME,Closed,Case Closed. Closed date : Wed May 15 06:58:54...,Improper Storage of Trash (Barrels),Public Works Department,Code Enforcement,Improper Storage of Trash (Barrels),PWDx_Code Enforcement,PWDx,NaN,https://spot-boston-res.cloudinary.com/image/u...,160-162 Liverpool St East Boston MA 02128,1,09,1,A7,East Boston,1,Ward 1,0104,160-162 Liverpool St,2128.0,42.373879,-71.039800,Citizens Connect App
1,2,101005463184,2024-05-14 13:33:53,2024-07-22 04:30:00,2024-05-24 12:34:37,ONTIME,Closed,Case Closed. Closed date : Fri May 24 16:34:37...,Graffiti Removal,Property Management,Graffiti,Graffiti Removal,PROP_GRAF_GraffitiRemoval,PROP,NaN,https://spot-boston-res.cloudinary.com/image/u...,1660 Dorchester Ave Dorchester MA 02122,7,07,3,C11,Dorchester,7,Ward 16,1604,1660 Dorchester Ave,2122.0,42.293929,-71.061822,Citizens Connect App
2,3,101005837387,2024-12-31 02:11:57,2025-01-01 03:30:00,NaN,OVERDUE,Open,,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,Parking Enforcement,BTDT_Parking Enforcement,BTDT,NaN,NaN,416 Belgrade Ave West Roxbury MA 02132,12,06,6,E5,West Roxbury,12,Ward 20,2011,416 Belgrade Ave,2132.0,42.285790,-71.149281,Citizens Connect App
3,4,101005287893,2024-02-07 04:01:41,2024-02-09 04:01:43,2024-02-07 05:48:33,ONTIME,Closed,Case Closed. Closed date : Wed Feb 07 10:48:33...,Improper Storage of Trash (Barrels),Public Works Department,Code Enforcement,Improper Storage of Trash (Barrels),PWDx_Code Enforcement,PWDx,NaN,https://spot-boston-res.cloudinary.com/image/u...,3 Saint Charles St Boston MA 02116,4,1C,2,D4,South End,6,Ward 5,0501,3 Saint Charles St,2116.0,42.347130,-71.071811,Citizens Connect App
4,5,101005331785,2024-02-28 08:06:00,2024-02-29 08:06:25,2024-03-04 09:07:57,OVERDUE,Closed,Case Closed. Closed date : 2024-03-04 14:07:57...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,Parking Enforcement,BTDT_Parking Enforcement,BTDT,NaN,NaN,47 Torrey St Dorchester MA 02124,8,07,4,B3,Dorchester,9,Ward 17,1708,47 Torrey St,2124.0,42.287380,-71.073564,Constituent Call

In [444]:
#Checking null values and deciding how to deal with them
df.isnull().sum().sort_values(ascending=False)

submitted_photo                   282836
closed_photo                      196042
location_zipcode                   57967
closed_date                        40802
sla_target_date                    22982
location_street_name                2745
longitude                           2158
latitude                            2158
fire_district                        513
neighborhood                         213
precinct                             109
case_topic                            89
public_works_district                 67
police_district                       64
neighborhood_services_district         5
city_council_district                  5
ward                                   0
system_generated_id                    0
location                               0
case_id                                0
assignment_department                  0
queue                                  0
service_name                           0
assigned_team                          0
assigned_department                    0
closure_reason                         0
case_status                            0
on_time                                0
open_date                              0
source                                 0
dtype: int64

In [445]:
# Correct way to check nulls and empty spaces
null_counts = df.isna().sum()

empty_string_counts = df.apply(
    lambda col: col.astype("string").str.strip().eq("").sum()
)
missing_summary = pd.DataFrame({
    "null_values": null_counts,
    "empty_or_whitespace_strings": empty_string_counts,
    "total_missing_like": null_counts + empty_string_counts
}).sort_values("total_missing_like", ascending=False)

missing_summary

,null_values,empty_or_whitespace_strings,total_missing_like
submitted_photo,282836,0,282836
closed_photo,196042,0,196042
location_zipcode,57967,0,57967
closure_reason,0,41031,41031
closed_date,40802,0,40802
sla_target_date,22982,0,22982
precinct,109,3614,3723
fire_district,513,2863,3376
neighborhood,213,2745,2958
public_works_district,67,2791,2858
police_district,64,2789,2853
city_council_district,5,2745,2750
neighborhood_services_district,5,2745,2750
ward,0,2745,2745
location,0,2745,2745
location_street_name,2745,0,2745
latitude,2158,0,2158
longitude,2158,0,2158
case_topic,89,0,89
system_generated_id,0,0,0
case_id,0,0,0
assignment_department,0,0,0
queue,0,0,0
service_name,0,0,0
assigned_team,0,0,0
assigned_department,0,0,0
case_status,0,0,0
on_time,0,0,0
open_date,0,0,0
source,0,0,0

In [446]:
# Checking all the zip code are of length of 4 so that I can append 0 in front of it 
# It is coming 6 because of length of characters
# This confirms that all the value are of length 4
(df["location_zipcode"].astype("string").str.len() == 6).any()

np.True_

In [447]:
# Chaning datatype of location_zipcode column from float to string and adding NA for null values
df["location_zipcode"] = (df["location_zipcode"].replace({None:pd.NA, "":pd.NA}).astype("string").str.replace(r"\.0$", "", regex=True))

In [448]:
# Padding 0 in the location_zipcode column
df["location_zipcode"] = df["location_zipcode"].str.zfill(5)

In [449]:
df["location_zipcode"].head(5)

0    02128
1    02122
2    02132
3    02116
4    02124
Name: location_zipcode, dtype: string

In [450]:
# The location_zipcode column was originally stored as a numeric type, which resulted in the loss of leading zeros for valid ZIP codes 
# (e.g., 02128 becoming 2128). Since ZIP codes are identifiers rather than numeric quantities, the column was standardized to a string 
# data type to preserve formatting and allow for missing values.

# An attempt was made to recover missing ZIP codes by extracting them from the location field. However, analysis showed that 57,967 
# records do not contain any ZIP code information within the location string itself. As a result, ZIP values for these records cannot 
# be reliably inferred through string parsing alone.

# To maintain data integrity and avoid introducing assumptions, these values have been retained as missing (NA). Future enrichment 
# (e.g., ZIP inference using latitude/longitude) may be considered if higher geographic completeness is required.

In [456]:
# Replacing NAN values in column location_street_name with pd.NA


# Note on location_street_name Data Handling
# The location_street_name column contains a limited number of missing values. An attempt was made to recover these 
# values by extracting the street name from the location field. However, further inspection showed that for every 
# record where location_street_name is missing, the corresponding location value is also missing or contains no usable address information.

# As a result, the street name cannot be reliably derived from other available columns. To preserve data integrity and avoid 
# introducing assumptions, these values have been retained as missing and standardized to NA.

df["location_street_name"] = df["location_street_name"].replace({np.nan:pd.NA})

In [ ]:
# Replacing NAN values in column submitted_photo with pd.NA
df["submitted_photo"] = df["submitted_photo"].replace({np.nan:pd.NA})

# Replacing NAN values in column closed_photo with pd.NA
df["closed_photo"] = df["closed_photo"].replace({np.nan:pd.NA})

# Replacing NAN values in column submitted_photo with pd.NA
df["submitted_photo"] = df["submitted_photo"].replace({np.nan:pd.NA})

# Replacing NAN values in column sla_target_date with pd.NA
df["sla_target_date"] = df["sla_target_date"].replace({np.nan:pd.NA})

# Replacing NAN values in column longitude with pd.NA 
df["longitude"] = df["longitude"].replace({np.nan:pd.NA})

# Replacing NAN values in column latitude with pd.NA 
df["latitude"] = df["latitude"].replace({np.nan:pd.NA})

# Replacing NAN values in column fire_district with pd.NA 
df["fire_district"] = df["fire_district"].replace({np.nan:pd.NA})

# Replacing NAN values in column neighborhood with pd.NA 
df["neighborhood"] = df["neighborhood"].replace({np.nan:pd.NA})

# Replacing NAN values in column precinct with pd.NA 
df["precinct"] = df["precinct"].replace({np.nan:pd.NA})

# Replacing NAN values in column case_topic with pd.NA 
df["case_topic"] = df["case_topic"].replace({np.nan:pd.NA})

# Replacing NAN values in column public_works_district with pd.NA 
df["public_works_district"] = df["public_works_district"].replace({np.nan:pd.NA})

# Replacing NAN values in column police_district with pd.NA 
df["police_district"] = df["police_district"].replace({np.nan:pd.NA})

# Replacing NAN values in column neighborhood_services_district with pd.NA 
df["neighborhood_services_district"] = df["neighborhood_services_district"].replace({np.nan:pd.NA})

# Replacing NAN values in column city_council_district with pd.NA 
df["city_council_district"] = df["city_council_district"].replace({np.nan:pd.NA})

# Replacing all the empty string in the data frame with pd.NA
df = df.apply(
    lambda col: col.replace(r'^\s*$', pd.NA, regex=True)
    if col.dtype == "object" or col.dtype.name == "string"
    else col
)

In [468]:
#Checking null values after making all the changes
df.isnull().sum().sort_values(ascending=False)

submitted_photo                   282836
closed_photo                      196042
location_zipcode                   57967
closure_reason                     41031
closed_date                        40802
sla_target_date                    22982
precinct                            3723
fire_district                       3376
neighborhood                        2958
public_works_district               2858
police_district                     2853
city_council_district               2750
neighborhood_services_district      2750
ward                                2745
location                            2745
location_street_name                2745
latitude                            2158
longitude                           2158
case_topic                            89
system_generated_id                    0
case_id                                0
assignment_department                  0
queue                                  0
service_name                           0
assigned_team                          0
assigned_department                    0
case_status                            0
on_time                                0
open_date                              0
source                                 0
dtype: int64

In [469]:
# Checking the empty of whitespace after replacing them with pd.NA

null_counts = df.isna().sum()

empty_string_counts = df.apply(
    lambda col: col.astype("string").str.strip().eq("").sum()
)
missing_summary = pd.DataFrame({
    "null_values": null_counts,
    "empty_or_whitespace_strings": empty_string_counts,
    "total_missing_like": null_counts + empty_string_counts
}).sort_values("total_missing_like", ascending=False)

missing_summary

,null_values,empty_or_whitespace_strings,total_missing_like
submitted_photo,282836,0,282836
closed_photo,196042,0,196042
location_zipcode,57967,0,57967
closure_reason,41031,0,41031
closed_date,40802,0,40802
sla_target_date,22982,0,22982
precinct,3723,0,3723
fire_district,3376,0,3376
neighborhood,2958,0,2958
public_works_district,2858,0,2858
police_district,2853,0,2853
city_council_district,2750,0,2750
neighborhood_services_district,2750,0,2750
ward,2745,0,2745
location,2745,0,2745
location_street_name,2745,0,2745
latitude,2158,0,2158
longitude,2158,0,2158
case_topic,89,0,89
system_generated_id,0,0,0
case_id,0,0,0
assignment_department,0,0,0
queue,0,0,0
service_name,0,0,0
assigned_team,0,0,0
assigned_department,0,0,0
case_status,0,0,0
on_time,0,0,0
open_date,0,0,0
source,0,0,0

In [470]:
# Checking if the case id is unique
df["case_id"].is_unique

True

In [471]:
#Checking is any record exist where open_date is greater then close_date
is_greater = (df["open_date"] > df["closed_date"]).any()
is_greater

np.True_

In [472]:
#Checking is sla_target_date is smaller then open_date or not
is_bigger = (df["sla_target_date"] < df["open_date"]).any()
is_bigger

np.False_

In [474]:
# Normalising the ward column and keeping the format "NumberNumber"
import re
word_to_remove = "Ward"
pattern = r'\b' + re.escape(word_to_remove) + r'\b'
df["ward"] = df['ward'].str.replace(pattern, '', regex=True, case=False).str.strip()

#Remove leading zeroes
df["ward"] = df["ward"].str.lstrip("0")

#Convert empty string creating by lstrip
df.loc[df["ward"].isin(["", "0"]), "ward"] = pd.NA

#Convert string to integer
df["ward"] = pd.to_numeric(df["ward"], errors="coerce").astype("Int64")

df["ward"].unique()

# When you first looked at the ward column, the issue was not missing data but inconsistent formatting. Some 
# records had “Ward 1”, some had “1”, some had “01”, and even values like “0” or “00”. Although some of these 
# represent the same district, grouping the data in its raw form would treat them as different categories. That 
# would split counts across multiple versions of the same ward and make your analysis inaccurate.

# What you did was standardize representation, not delete information. You removed the “Ward” prefix, stripped 
# leading zeros, converted invalid values like “0” into missing values, and then cast the column to a proper 
# numeric type. Now each ward is consistently stored as an integer between 1 and 22. This ensures correct grouping, 
# sorting, and aggregation in SQL, Excel, or BI tools.

# This is an important shift in thinking. Professional data work is less about filling nulls and more about 
# enforcing structural consistency. You did not change the meaning of the data. You made sure that the same 
# real-world district is represented in a single, consistent format across the dataset, which protects the 
# integrity of your future metrics and dashboards.

<IntegerArray>
[   1,   16,   20,    5,   17,   19,   10,   18,    2,   12,   14,   22,    7,
    9,    3,   11,   21,   15,    4,    6,    8,   13, <NA>]
Length: 23, dtype: Int64

In [475]:
df["assignment_department"].unique()

# df.loc[df["assignment_department"] == "Test"]

array(['PWDx', 'PROP', 'BTDT', 'ISD', 'INFO', 'GEN_', 'PARK', 'BWSC',
       'BPD_', 'ANML', 'BPS_', 'BHA_', 'ONS_', 'DND_', 'DISB', 'GRNi',
       'No Q', 'Test', 'ECON'], dtype=object)

In [481]:
# Converting all the datetime columns to datetime according to data dictionary
df["open_date"] = pd.to_datetime(df["open_date"], errors="coerce")
df["sla_target_date"] = pd.to_datetime(df["sla_target_date"], errors="coerce")
df["closed_date"] = pd.to_datetime(df["closed_date"], errors="coerce")

In [486]:
#Converting latitude and longitude to numeric
df["latitude"] = pd.to_numeric(df["latitude"], errors="coerce")
df["longitude"] = pd.to_numeric(df["longitude"], errors="coerce")

In [484]:
# Converting system_generated_id and case_id to string 
df["case_id"] = df["case_id"].astype("string")
df["system_generated_id"] = df["system_generated_id"].astype("string")

In [494]:
#Saving the cleaned dataframe to csv
df.to_csv("cases_clean_2024.csv", index=False)